# Generated by Django 5.2.5 on 2025-08-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_remove_orderitem_color_remove_orderitem_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
