# Generated by Django 5.2.5 on 2025-08-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
