# Generated by Django 5.2.5 on 2025-08-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_remove_orderitem_address_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
