# Generated by Django 5.2.5 on 2025-08-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_order_authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='authority',
        ),
    ]
