# Generated by Django 5.2.5 on 2025-08-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='آدرس ایمیل')),
                ('full_name', models.CharField(default='کاربر بدون نام', max_length=50, verbose_name='نام کامل')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کابری')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name=' شماره تلفن همراه ')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name=' ادمین ')),
            ],
            options={
                'verbose_name': ' کاربر ',
                'verbose_name_plural': ' کاربرها ',
            },
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
